In [1]:
import pandas as pd

df = pd.read_csv("ecommerce_uk_customers.csv")

df.head()

,customer_id,customer_name,gender,age,city,region,signup_date,total_spent,orders_count,preferred_category
0,C001,Customer 1,Female,33,Manchester,North West,2023-01-13,1154.89,24,Electronics
1,C002,Customer 2,Female,20,Leicester,East Midlands,2023-02-14,197.50,7,Fashion
2,C003,Customer 3,Male,53,Leicester,East Midlands,2023-11-05,1034.25,21,Sports
3,C004,Customer 4,Male,46,Leicester,East Midlands,2023-08-03,2966.87,1,Fashion
4,C005,Customer 5,Female,27,Sheffield,Yorkshire,2023-06-24,1115.80,25,Health

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         300 non-null    object
 1   customer_name       300 non-null    object
 2   gender              300 non-null    object
 3   age                 300 non-null    int64
 4   city                300 non-null    object
 5   region              300 non-null    object
 6   signup_date         300 non-null    object
 7   total_spent         300 non-null    float64
 8   orders_count        300 non-null    int64
 9   preferred_category  300 non-null    object
dtypes: float64(1), int64(2), object(7)
memory usage: 23.6+ KB

In [4]:
# Select multiple columns
df[["customer_name", "age"]]

    customer_name  age
0      Customer 1   33
1      Customer 2   20
2      Customer 3   53
3      Customer 4   46
4      Customer 5   27
..            ...  ...
295  Customer 296   23
296  Customer 297   57
297  Customer 298   28
298  Customer 299   19
299  Customer 300   54

[300 rows x 2 columns]

In [8]:
# Basic Analysis
total_amount = df['total_spent'].sum()

print("Total Amount spent: ",total_amount)

Total Amount spent:  776627.1799999999

In [10]:
total_orders = df['orders_count'].sum()

print("Total Orders:", total_orders)

Total Orders: 3962

In [11]:
average_amount = df['total_spent'].mean()

print("Average amount spent:", average_amount)

Average amount spent: 2588.7572666666665

In [15]:
# Sales greater than the average

high_sales = df[df['total_spent'] > 4900] #Filtring

high_sales

,customer_id,customer_name,gender,age,city,region,signup_date,total_spent,orders_count,preferred_category
27,C028,Customer 28,Female,43,Leeds,Yorkshire,2024-01-01,4975.99,21,Health
64,C065,Customer 65,Female,61,Liverpool,North West,2023-11-25,4906.69,18,Health
77,C078,Customer 78,Male,33,Birmingham,Midlands,2023-01-13,4920.48,20,Electronics
114,C115,Customer 115,Female,45,Leicester,East Midlands,2023-09-29,4983.33,18,Health
165,C166,Customer 166,Female,40,Birmingham,Midlands,2023-02-07,4938.88,10,Sports
195,C196,Customer 196,Male,21,Bristol,South West,2023-08-23,4993.00,13,Home
234,C235,Customer 235,Male,39,London,London,2023-08-19,4912.81,3,Beauty
276,C277,Customer 277,Female,57,London,London,2024-01-08,4990.85,9,Sports
288,C289,Customer 289,Male,25,Birmingham,Midlands,2023-07-05,4926.41,5,Fashion

In [20]:
# Maximum
# print(df['total_spent'].max())
df[df['total_spent'] == df['total_spent'].max()]

,customer_id,customer_name,gender,age,city,region,signup_date,total_spent,orders_count,preferred_category
195,C196,Customer 196,Male,21,Bristol,South West,2023-08-23,4993.0,13,Home

In [19]:
# Minimum

df[df['total_spent'] == df['total_spent'].min()]

,customer_id,customer_name,gender,age,city,region,signup_date,total_spent,orders_count,preferred_category
189,C190,Customer 190,Male,56,Liverpool,North West,2024-02-01,64.04,5,Fashion

In [22]:
# Sales per region

df['region'].value_counts()

region
East Midlands    63
North West       61
Yorkshire        60
Midlands         32
London           31
South West       27
South East       26
Name: count, dtype: int64

In [23]:
# number of sales per city

df['city'].value_counts()

city
Sheffield     32
Birmingham    32
Nottingham    32
Manchester    31
Leicester     31
London        31
Liverpool     30
Leeds         28
Bristol       27
Reading       26
Name: count, dtype: int64

In [27]:
# Total spent per region

region_sales = df.groupby("region")[['total_spent', 'orders_count']].sum()

print(region_sales)

               total_spent  orders_count
region
East Midlands    154264.51           792
London            83263.82           371
Midlands          81883.56           472
North West       154823.08           834
South East        61882.83           353
South West        73307.06           429
Yorkshire        167202.32           711

In [28]:
# Total Orders per region

region_sales = df.groupby("city")[['total_spent', 'orders_count']].sum()

print(region_sales)

            total_spent  orders_count
city
Birmingham     81883.56           472
Bristol        73307.06           429
Leeds          85112.03           381
Leicester      74337.78           414
Liverpool      68143.32           409
London         83263.82           371
Manchester     86679.76           425
Nottingham     79926.73           378
Reading        61882.83           353
Sheffield      82090.29           330

In [29]:
# Sales per Category

category_sales = df.groupby('preferred_category')['total_spent'].sum()

category_sales

preferred_category
Beauty         152314.84
Electronics    100643.56
Fashion        133647.22
Health         152253.03
Home           111195.16
Sports         126573.37
Name: total_spent, dtype: float64

In [30]:
# Sorting (ASC)

category_sales.sort_values()

preferred_category
Electronics    100643.56
Home           111195.16
Sports         126573.37
Fashion        133647.22
Health         152253.03
Beauty         152314.84
Name: total_spent, dtype: float64

In [31]:
# Sorting (DESC)

category_sales.sort_values(ascending=False)

preferred_category
Beauty         152314.84
Health         152253.03
Fashion        133647.22
Sports         126573.37
Home           111195.16
Electronics    100643.56
Name: total_spent, dtype: float64

In [36]:
# Top 5 Cities by total amount spent

city_sales = df.groupby("city")['total_spent'].sum()

city_sales.sort_values(ascending=False).head(3)

city
Manchester    86679.76
Leeds         85112.03
London        83263.82
Name: total_spent, dtype: float64

In [37]:
# Bottom 3 Regions by Number of Orders

region_orders = df.groupby("region")['orders_count'].sum()

region_orders.sort_values().head(3)

region
South East    353
London        371
South West    429
Name: orders_count, dtype: int64